"""Curriculum data for NodeQuest.

The app keeps content separate from Streamlit UI so additional subjects can be
added without changing the quiz engine.
"""

TOPICS = {
    "Linear Systems": {
        "prerequisite": "Algebra",
        "level": "Advanced",
        "description": "Solve and interpret systems of equations.",
        "study_actions": [
            "Practice substitution and elimination on two-variable systems.",
            "Check solutions by plugging values back into both equations.",
        ],
    },
    "Algebra": {
        "prerequisite": "Exponents",
        "level": "Intermediate",
        "description": "Manipulate expressions and solve equations.",
        "study_actions": [
            "Review inverse operations and equation balancing.",
            "Practice factoring common quadratic patterns.",
        ],
    },
    "Exponents": {
        "prerequisite": "Multiplication",
        "level": "Intermediate",
        "description": "Use powers and exponent rules fluently.",
        "study_actions": [
            "Memorize product, quotient, and power rules.",
            "Expand powers to connect exponent notation with multiplication.",
        ],
    },
    "Multiplication": {
        "prerequisite": "Addition",
        "level": "Foundation",
        "description": "Use repeated addition and multiplication facts.",
        "study_actions": [
            "Practice fact families from 2 through 12.",
            "Break larger products into distributive chunks.",
        ],
    },
    "Addition": {
        "prerequisite": None,
        "level": "Foundation",
        "description": "Add whole numbers with place-value reasoning.",
        "study_actions": [
            "Practice carrying across tens and hundreds.",
            "Estimate before calculating to catch unreasonable answers.",
        ],
    },
    "Foundational Stats": {
        "prerequisite": "Addition",
        "level": "Foundation",
        "description": "Summarize small data sets with center measures.",
        "study_actions": [
            "Sort data before finding the median.",
            "Count repeated values carefully when finding the mode.",
        ],
    },
}


KNOWLEDGE_GRAPH = {
    topic: details["prerequisite"]
    for topic, details in TOPICS.items()
}


QUESTION_BANK = {
    "Linear Systems": [
        {
            "id": "linear_substitution_01",
            "question": "Solve the system: $x + y = 5$ and $2x - y = 1$. What is $x$?",
            "choices": ["1", "2", "3", "4"],
            "correct": 1,
            "difficulty": 3,
            "skill": "Substitution",
            "misconception": "Likely mixed up substitution or arithmetic while combining equations.",
            "explanation": "Adding the equations gives $3x = 6$, so $x = 2$.",
        },
        {
            "id": "linear_matrix_size_01",
            "question": "Matrix $A$ is $2\\times3$ and matrix $B$ is $3\\times2$. What is the size of $AB$?",
            "choices": ["$2\\times2$", "$3\\times3$", "$2\\times3$", "Undefined"],
            "correct": 0,
            "difficulty": 3,
            "skill": "Matrix dimensions",
            "misconception": "May not yet connect inner dimensions with whether multiplication is valid.",
            "explanation": "The inner dimensions match, and the result uses the outer dimensions: $2\\times2$.",
        },
        {
            "id": "linear_elimination_01",
            "question": "Solve: $3x + y = 10$ and $x - y = 2$. What is $x$?",
            "choices": ["2", "3", "4", "6"],
            "correct": 1,
            "difficulty": 3,
            "skill": "Elimination",
            "misconception": "Likely needs more practice combining equations to remove a variable.",
            "explanation": "Adding the equations gives $4x = 12$, so $x = 3$.",
        },
        {
            "id": "linear_substitution_02",
            "question": "Solve: $y = 2x + 1$ and $y = 7$. What is $x$?",
            "choices": ["2", "3", "4", "6"],
            "correct": 1,
            "difficulty": 3,
            "skill": "Substitution",
            "misconception": "May not be replacing one variable with an equivalent expression.",
            "explanation": "Set $2x+1=7$, so $2x=6$ and $x=3$.",
        },
        {
            "id": "linear_elimination_02",
            "question": "Solve: $2x + 3y = 12$ and $2x - y = 4$. What is $y$?",
            "choices": ["1", "2", "3", "4"],
            "correct": 1,
            "difficulty": 3,
            "skill": "Elimination",
            "misconception": "May need to subtract equations carefully when coefficients match.",
            "explanation": "Subtract the second equation from the first: $4y=8$, so $y=2$.",
        },
        {
            "id": "linear_intersection_01",
            "question": "The lines $y=x+2$ and $y=-x+6$ intersect at which $x$-value?",
            "choices": ["1", "2", "3", "4"],
            "correct": 1,
            "difficulty": 3,
            "skill": "Graph interpretation",
            "misconception": "May not connect intersection points with equal output values.",
            "explanation": "Set $x+2=-x+6$, so $2x=4$ and $x=2$.",
        },
    ],
    "Algebra": [
        {
            "id": "algebra_equation_01",
            "question": "If $2x + 5 = 13$, what is $x$?",
            "choices": ["3", "4", "6", "8"],
            "correct": 1,
            "difficulty": 2,
            "skill": "One-step inverse operations",
            "misconception": "May be skipping the subtract-then-divide order of operations.",
            "explanation": "Subtract 5 to get $2x = 8$, then divide by 2: $x = 4$.",
        },
        {
            "id": "algebra_factoring_01",
            "question": "Factor $x^2 - 9$.",
            "choices": ["$(x-3)(x-3)$", "$(x+3)(x-3)$", "$(x+9)(x-1)$", "$x(x-9)$"],
            "correct": 1,
            "difficulty": 2,
            "skill": "Difference of squares",
            "misconception": "May not recognize $a^2-b^2=(a+b)(a-b)$.",
            "explanation": "$x^2 - 9$ is $x^2 - 3^2$, so it factors as $(x+3)(x-3)$.",
        },
        {
            "id": "algebra_simplify_01",
            "question": "Simplify $4(x - 2) + 3x$.",
            "choices": ["$7x - 8$", "$7x - 2$", "$4x - 8$", "$x - 8$"],
            "correct": 0,
            "difficulty": 2,
            "skill": "Distributive property",
            "misconception": "May be distributing only to the first term or not combining like terms.",
            "explanation": "$4(x-2)+3x = 4x-8+3x = 7x-8$.",
        },
        {
            "id": "algebra_equation_02",
            "question": "Solve $5x - 4 = 21$.",
            "choices": ["3", "4", "5", "6"],
            "correct": 2,
            "difficulty": 2,
            "skill": "Inverse operations",
            "misconception": "May need to undo subtraction before division.",
            "explanation": "Add 4 to get $5x=25$, then divide by 5: $x=5$.",
        },
        {
            "id": "algebra_like_terms_01",
            "question": "Combine like terms: $6a + 3 - 2a + 8$.",
            "choices": ["$4a+11$", "$8a+11$", "$4a+5$", "$6a+9$"],
            "correct": 0,
            "difficulty": 2,
            "skill": "Combining like terms",
            "misconception": "May be combining variable terms with constants.",
            "explanation": "$6a-2a=4a$ and $3+8=11$, so the expression is $4a+11$.",
        },
        {
            "id": "algebra_factoring_02",
            "question": "Factor $x^2 + 5x + 6$.",
            "choices": ["$(x+1)(x+6)$", "$(x+2)(x+3)$", "$(x-2)(x-3)$", "$(x+5)(x+1)$"],
            "correct": 1,
            "difficulty": 2,
            "skill": "Factoring trinomials",
            "misconception": "May need to find factor pairs that multiply to the constant and add to the middle coefficient.",
            "explanation": "$2$ and $3$ multiply to $6$ and add to $5$, so $(x+2)(x+3)$.",
        },
    ],
    "Exponents": [
        {
            "id": "exponents_evaluate_01",
            "question": "Evaluate $2^3$.",
            "choices": ["6", "8", "9", "12"],
            "correct": 1,
            "difficulty": 2,
            "skill": "Exponent meaning",
            "misconception": "May be multiplying the base by the exponent instead of repeated multiplication.",
            "explanation": "$2^3$ means $2\\times2\\times2 = 8$.",
        },
        {
            "id": "exponents_product_rule_01",
            "question": "Simplify $x^5 \\cdot x^3$.",
            "choices": ["$x^2$", "$x^{15}$", "$x^8$", "$2x^8$"],
            "correct": 2,
            "difficulty": 2,
            "skill": "Product rule",
            "misconception": "May be multiplying exponents instead of adding them for like bases.",
            "explanation": "When bases match, add exponents: $x^{5+3}=x^8$.",
        },
        {
            "id": "exponents_power_rule_01",
            "question": "Simplify $(a^2)^4$.",
            "choices": ["$a^6$", "$a^8$", "$a^{16}$", "$4a^2$"],
            "correct": 1,
            "difficulty": 2,
            "skill": "Power rule",
            "misconception": "May need to distinguish multiplying exponents from adding exponents.",
            "explanation": "A power raised to a power multiplies exponents: $a^{2\\cdot4}=a^8$.",
        },
        {
            "id": "exponents_quotient_rule_01",
            "question": "Simplify $m^9 \\div m^4$.",
            "choices": ["$m^5$", "$m^{13}$", "$m^{36}$", "$5m$"],
            "correct": 0,
            "difficulty": 2,
            "skill": "Quotient rule",
            "misconception": "May be adding exponents when division requires subtraction.",
            "explanation": "For matching bases, subtract exponents: $m^{9-4}=m^5$.",
        },
        {
            "id": "exponents_zero_rule_01",
            "question": "What is $7^0$?",
            "choices": ["0", "1", "7", "Undefined"],
            "correct": 1,
            "difficulty": 2,
            "skill": "Zero exponent",
            "misconception": "May think a zero exponent makes the whole expression zero.",
            "explanation": "Any nonzero number raised to the zero power equals 1.",
        },
        {
            "id": "exponents_negative_rule_01",
            "question": "Rewrite $3^{-2}$ with a positive exponent.",
            "choices": ["$\\frac{1}{3^2}$", "$-3^2$", "$3^2$", "$\\frac{1}{3^{-2}}$"],
            "correct": 0,
            "difficulty": 2,
            "skill": "Negative exponents",
            "misconception": "May treat a negative exponent as a negative number instead of a reciprocal.",
            "explanation": "A negative exponent moves the base to the denominator: $3^{-2}=\\frac{1}{3^2}$.",
        },
    ],
    "Multiplication": [
        {
            "id": "multiply_fact_01",
            "question": "Calculate $7 \\times 6$.",
            "choices": ["42", "36", "49", "48"],
            "correct": 0,
            "difficulty": 1,
            "skill": "Fact fluency",
            "misconception": "May need more recall practice with basic multiplication facts.",
            "explanation": "$7\\times6$ is seven groups of six, which is 42.",
        },
        {
            "id": "multiply_two_digit_01",
            "question": "What is $12 \\times 11$?",
            "choices": ["122", "131", "132", "144"],
            "correct": 2,
            "difficulty": 1,
            "skill": "Two-digit multiplication",
            "misconception": "May be close on place value but missing one partial product.",
            "explanation": "$12\\times11 = 12\\times10 + 12\\times1 = 120 + 12 = 132$.",
        },
        {
            "id": "multiply_distributive_01",
            "question": "Use mental math: $9 \\times 15$.",
            "choices": ["115", "125", "135", "145"],
            "correct": 2,
            "difficulty": 1,
            "skill": "Distributive reasoning",
            "misconception": "May need to break multiplication into easier chunks.",
            "explanation": "$9\\times15 = 9\\times(10+5)=90+45=135$.",
        },
        {
            "id": "multiply_fact_02",
            "question": "Calculate $8 \\times 7$.",
            "choices": ["48", "54", "56", "64"],
            "correct": 2,
            "difficulty": 1,
            "skill": "Fact fluency",
            "misconception": "May need more automatic recall of upper multiplication facts.",
            "explanation": "$8\\times7=56$.",
        },
        {
            "id": "multiply_area_01",
            "question": "A rectangle is 9 units long and 4 units wide. What is its area?",
            "choices": ["13", "26", "36", "40"],
            "correct": 2,
            "difficulty": 1,
            "skill": "Multiplication in context",
            "misconception": "May be adding side lengths instead of multiplying length by width.",
            "explanation": "Area is length times width: $9\\times4=36$.",
        },
        {
            "id": "multiply_place_value_01",
            "question": "What is $30 \\times 7$?",
            "choices": ["37", "70", "210", "300"],
            "correct": 2,
            "difficulty": 1,
            "skill": "Place-value multiplication",
            "misconception": "May be ignoring the zero in a multiple of ten.",
            "explanation": "$3\\times7=21$, then multiply by 10 to get 210.",
        },
    ],
    "Addition": [
        {
            "id": "addition_carry_01",
            "question": "What is $14 + 29$?",
            "choices": ["33", "43", "53", "45"],
            "correct": 1,
            "difficulty": 1,
            "skill": "Regrouping",
            "misconception": "May be missing the carry from ones into tens.",
            "explanation": "$14+29 = 10+20+4+9 = 30+13 = 43$.",
        },
        {
            "id": "addition_hundreds_01",
            "question": "Compute $125 + 375$.",
            "choices": ["450", "490", "500", "510"],
            "correct": 2,
            "difficulty": 1,
            "skill": "Place value",
            "misconception": "May need to align hundreds, tens, and ones carefully.",
            "explanation": "$125+375 = 500$.",
        },
        {
            "id": "addition_estimate_01",
            "question": "Which sum is closest to $198 + 403$?",
            "choices": ["400", "500", "600", "700"],
            "correct": 2,
            "difficulty": 1,
            "skill": "Estimation",
            "misconception": "May not be using rounding to check whether an answer is reasonable.",
            "explanation": "$198$ is near $200$ and $403$ is near $400$, so the sum is near $600$.",
        },
        {
            "id": "addition_two_digit_01",
            "question": "What is $68 + 27$?",
            "choices": ["85", "95", "96", "105"],
            "correct": 1,
            "difficulty": 1,
            "skill": "Two-digit addition",
            "misconception": "May need to regroup ones into a new ten.",
            "explanation": "$68+27 = 68+20+7 = 88+7 = 95$.",
        },
        {
            "id": "addition_missing_addend_01",
            "question": "What number makes this true: $46 + \\square = 100$?",
            "choices": ["44", "54", "56", "64"],
            "correct": 1,
            "difficulty": 1,
            "skill": "Missing addends",
            "misconception": "May need to connect subtraction with finding an unknown addend.",
            "explanation": "$100-46=54$, so the missing addend is 54.",
        },
        {
            "id": "addition_three_numbers_01",
            "question": "Compute $18 + 25 + 32$.",
            "choices": ["65", "70", "75", "85"],
            "correct": 2,
            "difficulty": 1,
            "skill": "Adding multiple numbers",
            "misconception": "May be losing track of partial sums across more than two addends.",
            "explanation": "$18+32=50$, and $50+25=75$.",
        },
    ],
    "Foundational Stats": [
        {
            "id": "stats_median_01",
            "question": "Find the median of $[3, 1, 9, 7, 5]$.",
            "choices": ["1", "3", "5", "7"],
            "correct": 2,
            "difficulty": 1,
            "skill": "Median",
            "misconception": "May be finding the middle before sorting the data.",
            "explanation": "Sort first: $[1,3,5,7,9]$. The middle value is 5.",
        },
        {
            "id": "stats_mode_01",
            "question": "What is the mode of $[4, 2, 4, 3, 2, 4]$?",
            "choices": ["2", "3", "4", "6"],
            "correct": 2,
            "difficulty": 1,
            "skill": "Mode",
            "misconception": "May need to count frequencies before choosing the most common value.",
            "explanation": "The number 4 appears three times, more than any other value.",
        },
        {
            "id": "stats_mean_01",
            "question": "What is the mean of $[2, 4, 6, 8]$?",
            "choices": ["4", "5", "6", "8"],
            "correct": 1,
            "difficulty": 1,
            "skill": "Mean",
            "misconception": "May be summing correctly but dividing by the wrong number of values.",
            "explanation": "The sum is 20 and there are 4 values, so the mean is 5.",
        },
        {
            "id": "stats_range_01",
            "question": "What is the range of $[12, 4, 9, 15, 6]$?",
            "choices": ["9", "10", "11", "15"],
            "correct": 2,
            "difficulty": 1,
            "skill": "Range",
            "misconception": "May be choosing the largest value instead of subtracting smallest from largest.",
            "explanation": "The range is $15-4=11$.",
        },
        {
            "id": "stats_median_even_01",
            "question": "Find the median of $[2, 10, 4, 8]$.",
            "choices": ["4", "6", "7", "8"],
            "correct": 1,
            "difficulty": 1,
            "skill": "Median with even counts",
            "misconception": "May need to average the two middle values after sorting.",
            "explanation": "Sort to $[2,4,8,10]$. The middle values are 4 and 8, and their average is 6.",
        },
        {
            "id": "stats_frequency_01",
            "question": "In $[1, 3, 3, 3, 5, 5, 8]$, how many times does 3 appear?",
            "choices": ["2", "3", "4", "5"],
            "correct": 1,
            "difficulty": 1,
            "skill": "Frequency",
            "misconception": "May need to count occurrences systematically before summarizing data.",
            "explanation": "The value 3 appears three times.",
        },
    ],
}


def topic_order():
    """Return topics from foundations toward advanced concepts."""
    return sorted(TOPICS, key=lambda topic: _depth(topic))


def _depth(topic):
    depth = 0
    parent = KNOWLEDGE_GRAPH[topic]
    while parent:
        depth += 1
        parent = KNOWLEDGE_GRAPH[parent]
    return depth
